config/routes.rb
Rails.application.routes.draw do
  get 'topics/index'
  get 'topics/show'
  get 'topics/new'
  get 'topics/edit'
  # kind of route
  # controller#method_name
  root 'subs#index'

  # get 'subs/new'
  # get '/turkey', to: 'subs#new'

  # post '/subs', to: 'subs#create'
  # #  :id placeholder for the id number
  # put '/subs/:id', to: 'subs#update'
  # delete '/subs/:id', to: 'subs#delete'

  # embeded routes, nested routes
  resources :subs do
    resources :topics
  end

  resources :topics do
    resources :comments
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic
end

app/models/sub.rb
class Sub < ApplicationRecord
  has_many :topics
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :sub
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # before_action :verify_paid

  def verify_paid
    paid = true
  end

  # user login

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_topic

  # get
  def new
    @comment = Comment.new
    # form
  end

  # post
  def create
    @comment = @topic.comments.new(comments_params)
  end

  private 
    def comments_params
      params.require(:comment).permit(:body, :author)
    end

    def set_topic
      @topic = Topic.find(params[:id])
    end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  # skinny controllers, fat models
    # controller to be slim as possible
      # D.R.Y. and only worry about actions
      # CRUD: Create, Read, Update & Delete

      # index   @ppl = Person.all
      # show    @person = Person.find(params[:id])
      # new     @person = Person.new
      # create  @person = Person.create(ppl_params)
      # edit    @person = Person.find(params[:id])
      # update  @person = Person.find(params[:id]).update(ppl_params)
      # delete  @person = Person.find(params[:id]).destroy

      # callbacks
        # before_action
          # called before entering a method
        # after_action
          # called after entering a method
        # skip_before_action
          # skip before action
        # skip_after_action
          # skip after action
        
        # EXAMPLE
        # before_action :method_to_call, (only/except): [:index, :show]

    # Models, all logic code
    # ordering, printing

  before_action :set_sub, only: [:show, :update, :edit, :destroy]
  # before_action :set_sub, except: [:index, :new, :create]

  # TODO - anything that needs to be done
  # FIXME - fix any bugs or errors
  # OPTIMIZE - refactor

  # TODO fill out index view
  # FIXME page not loading
  # OPTIMIZE change the color of the text

  # in the terminal type bundle exec rake notes
  # get
  def index
    @subs = Sub.all
    # render a webpage/views
    # views/subs/index.html.erb

    # default render html
    # render return json, xml redirect
  end

  def show
    # defaults renders shows views/subs/show.html.erb
  end

  # get
  def new
    # creats a sub a memory
    @sub = Sub.new
    # renders the sub form
    render partial: "form"
  end

  # post
  def create
    @sub = Sub.create(sub_params)
    if @sub.save
      redirect_to root_path
    else
      render :new
    end
  end

  # get
  def edit
    # renders the sub form
    render partial: "form"
    # render 'subs/form' .... could write this
  end

  # put
  def update
    if @sub.update(sub_params)
      redirect_to @sub
    else
      render :edit
    end
  end

  # delete
  def destroy
    @sub.destroy
    redirect_to root_path
  end

  private
    def sub_params
      params.require(:sub).permit(:name)
    end

    def set_sub
      @sub = Sub.find(params[:id])
    end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_sub
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  def index
    @topics = @sub.topics
    # @sub.Topic.all
  end

  def show
  end

  def new
    @topic = @sub.topics.new
    render partial: "form"
  end

  def create
    @topic = @sub.topics.create(topic_params)
    if @topic.save
      redirect_to [@sub, @topic]
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @topic.update(topic_params)
      redirect_to [@sub, @topic]
    else
      render :edit
    end
  end

  def destroy
    @topic.destroy
    redirect_to sub_topics_path
  end

  private
    def set_sub
      @sub = Sub.find(params[:sub_id])
    end

    def set_topic
      @topic = Topic.find(params[:id])
    end
    
    def topic_params
      params.require(:topic).permit(:name, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/subs/_form.html.erb
<%= @sub.id ? 'Edit Sub': 'Create Sub' %>

<%= form_for @sub do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

app/views/subs/index.html.erb
<h1>Viewing all subs</h1>

<%= link_to 'Create new sub', new_sub_path %>

<% @subs.each do |sub| %>
  <%= link_to sub.name, sub %>
<% end %>

app/views/subs/new.html.erb
<h1>Subs#new</h1>
<p>Find me in app/views/subs/new.html.erb</p>

app/views/subs/show.html.erb
<h1><%= @sub.name %></h1>

<%= link_to 'view Topics', sub_topics_path(@sub) %>
<%= link_to 'edit sub', edit_sub_path(@sub) %>
<%= link_to 'delete sub', @sub, method: :delete %>

app/views/topics/_form.html.erb
<%= @topic.id ? "Edit Topic" : "create Topic" %>

<%= form_for [@sub, @topic] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<h1>Topics</h1>

<%= link_to 'Create a new topic', new_sub_topic_path(@sub) %>

<%= @topics.each do |topic| %>
  <%= link_to topic.name, [@sub, topic] %>

<% end %>

app/views/topics/new.html.erb
<h1>Topics#new</h1>
<p>Find me in app/views/topics/new.html.erb</p>

app/views/topics/show.html.erb
<h1><%= @sub.name %> - <%= @topic.name %></h1>

<%= @topic.body %>

<%= link_to 'edit topic', edit_sub_topic_path([@sub, @topic])  %>
<%= link_to 'Delete topic', [@sub, @topic], method: :delete %>
<%= link_to 'back to topic', sub_topics_path(@sub) %>